Models/BD.cs
using  Microsoft.Data.SqlClient;
using Dapper;
public static class BD{
    private static string _connectionString = @"Server=localhost; DataBase=TP06_repaso-PatejimFeldman; Integrated Security=True; TrustServerCertificate=True;";
    public static int Login(string username, string password){
        int aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "SELECT id FROM Usuario WHERE password = @password AND username = @username";
            aux = connection.QueryFirstOrDefault<int>(query, new {username, password});

        }
        return aux;
    }
    public static int VerificarUsuario(string username){
        int aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "SELECT id FROM Usuario WHERE username = @username";
            aux = connection.QueryFirstOrDefault<int>(query, new {username});

        }
        return aux;
    }
    public static void Registrar(Usuario usu){
        string query = "INSERT INTO Usuario (username, password, nombre, apellido, foto) VALUES (@username, @password, @nombre, @apellido, @foto)";
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            connection.Execute(query, new {username = usu.username, password = usu.password, nombre = usu.nombre, apelldio = usu.apellido, foto = usu.foto});
        }
    }









    public static Tarea AgregarTarea(Tarea tarea){
        Tarea aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "INSERT INTO Usuario (Titulo, Descripcion, Fecha, Finalizada) VALUES (@Titulo, @Descripcion, @Fecha, @Finalizada)";
            aux = connection.QueryFirstOrDefault<Tarea>(query, new {tarea});

        }
        return aux;
    }
    public static void ModificarTarea(Tarea tarea){
        Tarea aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "UPDATE Tarea SET Titulo = @Titulo, Descripcion = @Descripcion, Fecha = @Fecha, Finalizada = @Finalizada WHERE id = @id";
            aux = connection.QueryFirstOrDefault<Tarea>(query, new {tarea});

        }
    }
        
    public static void FinalizarTarea(int id){
        
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "UPDATE Tarea SET finalizada = 1 WHERE id = @id";
            connection.Execute(query, new{id});

        }
        
    }
    public static Tarea VerTarea(int id){
        Tarea aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "SELECT * FROM Tarea WHERE id = @id";
            aux = connection.QueryFirstOrDefault<Tarea>(query, new {id});

        }
        return aux;
    }
    public static List<Tarea> VerTareas(int id_Usuario){
        List<Tarea> aux;
        using(SqlConnection connection = new SqlConnection(_connectionString))
        {
            
            string query = "SELECT * FROM Tarea";
            aux = connection.Query<Tarea>(query, new {id_Usuario}).ToList();

        }
        return aux;
    }
    
    


}

Models/ErrorViewModel.cs
namespace TP06.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Tarea.cs
using Newtonsoft.Json;
public class Tarea
{
    [JsonProperty]
    public string Titulo {get; private set;}
    [JsonProperty]
    public string Descripcion {get; private set;}
    [JsonProperty]
    public DateTime Fecha {get; private set;}
    [JsonProperty]
    public bool Finalizada {get; private set;}

    public Tarea(string Titulo, string Descripcion, DateTime Fecha, bool Finalizada){
        this.Titulo=Titulo;
        this.Descripcion=Descripcion;
        this.Fecha=Fecha;
        this.Finalizada=Finalizada;
    }
}

Models/Usuario.cs
using Newtonsoft.Json;

public class Usuario 
{
     [JsonProperty]
    public int id{get; private set;}
     [JsonProperty]
    public string username{get; private set;}
     [JsonProperty]
    public string password{get; private set;}
     [JsonProperty]
    public string nombre{get; private set;}
     [JsonProperty]
    public string apellido{get; private set;}
     [JsonProperty]
    public string foto{get; private set;}
     [JsonProperty]
    public DateTime fechaLastLogIn{get; private set;}

    public Usuario(string username, string password, string nombre, string apellido, string foto, DateTime fechaLastLogIn){
        this.username=username;
        this.password=password;
        this.nombre=nombre;
        this.apellido=apellido;
        this.foto=foto;
        this.fechaLastLogIn=fechaLastLogIn;
    }
}

Controllers/AcountController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TP06.Models;

namespace TP06.Controllers;


public class AcountController : Controller
{
    private readonly ILogger<AcountController> _logger;

    public AcountController(ILogger<AcountController> logger)
    {
        _logger = logger;
    }

    public IActionResult LogIn()
    {
        return View("LogIn");
    }

    public IActionResult LogInGuardar(string username, string password){
        int id = BD.Login(username, password);
        if(id == 0){
            return View("ErrorLogIn");  
        }else{
            HttpContext.Session.SetString("idUser", id.ToString());
            
            return View("Personal");
        }
    }

    public IActionResult SignIn()
    {
        return View("SignIn");
    }

    public IActionResult SignInGuardar(string username, string password, string nombre, string apellido){
        int id = BD.VerificarUsuario(username);
        if(id != 0){
            return View("ErrorSignIn");
        }else{
            
            return View("Personal");
        }
    }
    public IActionResult CerrarSesion(){
        HttpContext.Session.Clear();
        return View("CerrarSesion");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TP06.Models;

namespace TP06.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Volver(){
        return View("Index");
    }

    public IActionResult VerTareas(){
        
    }
}

Views/Acount/CerrarSesion.cshtml
<h1>Se cerró la sesion con exito</h1>
<form action='@Url.Action("Volver", "Home")' method ="post"> 
    <input type="submit" name = "VOLVER">
</form>

Views/Acount/ErrorLogIn.cshtml
<h1>Este usuario no existe</h1>
<form action='@Url.Action("Volver", "Home")' method ="post"> 
    <input type="submit" name = "VOLVER">
</form>

Views/Acount/ErrorSignIn.cshtml
<h1>Este usuario ya existe</h1>
<form action='@Url.Action("Volver", "Home")' method ="post"> 
    <input type="submit" name = "VOLVER">
</form>

Views/Acount/LogIn.cshtml
<form action='@Url.Action("LogInGuardar", "Acount")' method ="post"> ver si aca va Acount o AcountController
    <h2>Nombre de Usuario:</h2>
    <input type = "text" name = "username" required>
    <h2>Contraseña:</h2>
    <input type = "password" name = "password" required>
    <input type="submit" name = "enviar">
</form>
<form action='@Url.Action("Volver", "Home")' method ="post"> 
    <input type="submit" name = "VOLVER">
</form>

Views/Acount/SignIn.cshtml
<form action='@Url.Action("SignInGuardar", "Acount")' method ="post"> ver si aca va Acount o AcountController
    <h2>Nombre de Usuario:</h2>
    <input type = "text" name = "username" required>
    <h2>Contraseña:</h2>
    <input type = "password" name = "password" required>
    <h2>Nombre:</h2>
    <input type = "text" name = "Nombre" required>
    <h2>Apellido:</h2>
    <input type = "text" name = "Apellido" required>
    <input type="submit" name = "enviar">
</form>
<form action='@Url.Action("Volver", "Home")' method ="post"> 
    <input type="submit" name = "VOLVER">
</form>

Views/Home/Index.cshtml
<h1>Bienvenido a la lista de tareas</h1>
<form action='@Url.Action("LogIn", "Acount")' method ="post">   
    <input type="submit" name = "INICIAR SESION">
</form>
<form action='@Url.Action("SignIn", "Acount")' method ="post">   
    <input type="submit" name = "REGISTRARSE">
</form>

Views/Home/LogIn.cshtml
<form action='@Url.Action("LogInGuardar", "Acount")' method ="post"> ver si aca va Acount o AcountController
    <h2>Nombre de Usuario:</h2>
    <input type = "text" name = "username" required>
    <h2>Contraseña:</h2>
    <input type = "password" name = "password" required>
    <input type="submit" name = "enviar">
</form>

Views/Home/Personal.cshtml
<h1>TAREAS</h1>
@foreach(var idTarea in ViewBag.AIAIAIAAIAI){
<div>

</div>
}

Views/Home/SignIn.cshtml
<form action='@Url.Action("SignInGuardar", "Acount")' method ="post"> ver si aca va Acount o AcountController
    <h2>Nombre de Usuario:</h2>
    <input type = "text" name = "username" required>
    <h2>Contraseña:</h2>
    <input type = "password" name = "password" required>
    <h2>Nombre:</h2>
    <input type = "text" name = "Nombre" required>
    <h2>Apellido:</h2>
    <input type = "text" name = "Apellido" required>
    <input type="submit" name = "enviar">
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NombreProyecto</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body>
    <header>
        NombreProyecto
    </header>

    <main role="main">
        @RenderBody()
    </main>

    <footer>
        &copy; @DateTime.Now.Year - NombreProyecto
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>